name: Fetch Rainfall Data

permissions: 
  contents: write

on:
  schedule:
    - cron: "* * * * *"   # tiap 1 menit
  workflow_dispatch:      # bisa run manual

jobs:
  fetch-rainfall:
    runs-on: ubuntu-latest
    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      METEOBOT_5332353130313538_USER: ${{ secrets.METEOBOT_5332353130313538_USER }}
      METEOBOT_5332353130313538_PASS: ${{ secrets.METEOBOT_5332353130313538_PASS }}

      METEOBOT_5332353130313539_USER: ${{ secrets.METEOBOT_5332353130313539_USER }}
      METEOBOT_5332353130313539_PASS: ${{ secrets.METEOBOT_5332353130313539_PASS }}

      METEOBOT_5332353130313630_USER: ${{ secrets.METEOBOT_5332353130313630_USER }}
      METEOBOT_5332353130313630_PASS: ${{ secrets.METEOBOT_5332353130313630_PASS }}

      METEOBOT_5332353130313631_USER: ${{ secrets.METEOBOT_5332353130313631_USER }}
      METEOBOT_5332353130313631_PASS: ${{ secrets.METEOBOT_5332353130313631_PASS }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug root
        run: |
          pwd
          ls -la
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run rainfall fetch script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          python scripts/fetch_rainfall.py
      
      - name: Debug rainfall output
        run: |
          ls -la
          ls -la data || true
          ls -la data/rainfall || true

      - name: Commit and push data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add data/rainfall || true
          git commit -m "Update rainfall data" || echo "No changes to commit"
          git push
